apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-tracker-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: git@gitlab.com:matanp103/expense-app-gitops.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: expense-tracker
  syncPolicy:
      syncOptions:
        - CreateNamespace=true