
deployment: 
  name: expense-app-dep
  namespace: default
  podsName: expense-app-dep
  image:
    repository: 644435390668.dkr.ecr.ap-south-1.amazonaws.com/matan-protfolio
    tag: ""
  containerName: expense-app-container
  containerPort: 5000
  lables:
    app: expense-app-dep
  service:
    name: expense-app-service
    port: 80

cronJob:
  name: clear-mongodb-job
  enabled: false
  image: 
    name: mongo
    tag: latest
  containerName: clear-mongodb
  collectionName: 
  collectionCommand: deleteMany({})
  schedule: "0 0 * * *"

configMap:
  name: expense-app-conf

secret:
  external: true
  name: expense-app-secret
  type: Opaque

issuer:
  enabled: false
  name: letsencrypt-issuer
  server: https://acme-v02.api.letsencrypt.org/directory 
  email: matanp103@gmail.com
  privateKeyName: domain-name-secret


ingress:
  name: ingress-role
  enabled: true
  hosts:
    - host: matan-dns.hopto.org
  secretName: matan-dns-key

loadBalancer:
  name: expense-app-lb
  port: 80


mongodb:
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  nameOverride: mongodb
  containerPort:
    mongodb: 27017
  service:
    name: mongodb-headless
  architecture: replicaset
  replicaCount: 3
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  arbiter:
    enabled: false
  auth:
    enabled: true
    existingSecret: ""
    rootPassword: root
    rootUser: matan

  persistence:
    enabled: false
    name: "datadir"
    accessModes: ["ReadWriteOnce"]
    size: 8Gi

