crds:
  enabled: true

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: expense-tracker
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 30s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - matan-dns.servehttp.com



grafana:
  enabled: true
  persistence:
    enabled: true
    type: sts 
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection