apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: '4.10.1'
    helm:
      parameters:
        - name: controller.resources.requests.memory
          value: "128Mi"
        - name: controller.resources.requests.cpu
          value: "125m"
        - name: controller.resources.limits.memory
          value: "256Mi"
        - name: controller.resources.limits.cpu
          value: "250m"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true