{{- define "mongo" }}
  {{- $mongoHosts := "" -}}
  {{- $hosts := "" -}}
  {{- range $i := until (int $.Values.mongodb.replicaCount) -}}
    {{- $currHost := printf "%s-%s-%d" $.Release.Name $.Values.mongodb.nameOverride $i -}}
    {{- $currHost = printf "%s.%s-%s.%s.svc.cluster.local" $currHost $.Release.Name $.Values.mongodb.service.name $.Release.Namespace -}}
    {{- if $hosts -}}
      {{- $hosts = printf "%s,%s" $hosts $currHost -}}
    {{- else -}}
      {{- $hosts = $currHost -}}
    {{- end -}}
  {{- end -}}
  {{- $mongoHosts = printf "%s%s" $mongoHosts $hosts -}}
  {{ printf "%s/%s?replicaSet=%s" $mongoHosts (first .Values.mongodb.auth.databases) ( .Values.mongodb.replicaSetName | default "rs0" )  }}
{{- end }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  MONGODB_HOST: "{{ include "mongo" .}}"
  MONGODB_PORT: "{{ .Values.mongodb.containerPort.mongodb }}"
  MONGO_USERNAME: {{ first .Values.mongodb.auth.usernames }}