apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.lables.app }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.deployment.podsName }}
  template:
    metadata:
      name: {{ .Values.deployment.podsName }}
      labels:
        app: {{ .Values.deployment.podsName }}
    spec:
      containers:
      - name: {{  .Values.deployment.containerName }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: {{ .Values.deployment.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
          - secretRef:
              name: {{ .Values.secret.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.podsName }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}