{{- if .Values.issuer.enabled -}}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email:  {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.privateKeyName }}
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx

{{- end -}}