{{- if not .Values.mongodb.auth.existingSecret -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  MONGODB_USERNAME: {{ .Values.mongodb.auth.rootUser  | b64enc }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  
{{- end -}}